apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hawkeye
  title: hawkeye
  annotations:
    circleci.com/project-slug: github/choonsikdobbyidp/hawkeye
    github.com/project-slug: choonsikdobbyidp/hawkeye
    sonarqube.org/project-key: choonsikdobbyidp_hawkeye
    backstage.io/techdocs-ref: dir:.
    kong-manager/service-name: 0d9fc993-bbfa-4861-b862-a3a808125203
    kong-manager/instance: /kong-manager/api
    kong-manager/workspace: default
    argocd/app-name: vite-app
    nexus-repository-manager/docker.image-name: backstage-image
  links:
    - title: Prometheus
      url: https://google.ch
      icon: prometheus
    - title: Grafana
      url: https://google.ch
      icon: grafana
    - title: Google BigQuery
      url: https://google.ch
      icon: googlebigquery
    - title: 1.1.1.1
      url: https://google.ch
      icon: 1dot1dot1dot1
    - title: Github copilot
      url: https://google.ch
      icon: githubcopilot
    - title: Backstage
      url: https://google.ch
      icon: backstage
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: piotr.minkowski@gmail.com
  lifecycle: development

