apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hawkeye
  title: hawkeye
  annotations:
    circleci.com/project-slug: github/choonsikdobbyidp/hawkeye
    github.com/project-slug: choonsikdobbyidp/hawkeye
    sonarqube.org/project-key: choonsikdobbyidp_hawkeye
    argocd/app-name: vite-app
    nexus-repository-manager/docker.image-name: backstage-image
  links:
  - url: https://dashboard.example.com
    title: My Dashboard
    icon: dashboard
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: piotr.minkowski@gmail.com
  lifecycle: experimental
