apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: choonsikdobi1/vite-app:latest
        ports:
        - containerPort: 5433
---
apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
spec:
  selector:
    app: vite-app
  ports:
    - protocol: TCP
      port: 5433
      nodePort: 30080
  type: NodePort
